name: SpeakSmooth
options:
  bundleIdPrefix: com.speaksmooth
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.speaksmooth.app
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: 1
    ENABLE_HARDENED_RUNTIME: true
    CODE_SIGN_ENTITLEMENTS: SpeakSmooth/Resources/SpeakSmooth.entitlements

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.10.0"
  RealTimeCutVADLibrary:
    url: https://github.com/helloooideeeeea/RealTimeCutVADLibrary.git
    from: "1.0.14"
  MSAL:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc.git
    from: "1.6.1"

targets:
  SpeakSmooth:
    type: application
    platform: macOS
    sources:
      - path: SpeakSmooth
        excludes:
          - Resources/Info.plist
    info:
      path: SpeakSmooth/Resources/Info.plist
    entitlements:
      path: SpeakSmooth/Resources/SpeakSmooth.entitlements
    dependencies:
      - package: WhisperKit
      - package: RealTimeCutVADLibrary
      - package: MSAL
    settings:
      base:
        INFOPLIST_KEY_LSUIElement: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"

  SpeakSmoothTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SpeakSmoothTests
    dependencies:
      - target: SpeakSmooth
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SpeakSmooth.app/Contents/MacOS/SpeakSmooth"
